framework:
    messenger:
        transports:
            user_created:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\UserCreatedMessage: user_created

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
