version: '3'

services:
  web:
    image: nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rabbitmq
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - rabbitmq
    expose:
      - 9000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    networks:
      - rabbitmq
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    networks:
      - rabbitmq
    ports:
      - "8080:8080"

networks:
  rabbitmq:
    driver: bridge